LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Box2D-prebuilt
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/libBox2D.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../../include
TARGET_PLATFORM = android-8
include $(PREBUILT_STATIC_LIBRARY)
