LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := NvEvent
LOCAL_SRC_FILES :=   $(TARGET_ARCH_ABI)/libNvEvent.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../jni
LOCAL_EXPORT_CFLAGS := -DANDROID
LOCAL_EXPORT_CPPFLAGS := -DANDROID

include $(PREBUILT_STATIC_LIBRARY)

